1. Data
2. Preprocessing
3. Splitting
4. Building NN
5. Evaluate

#### [Imported data from](https://archive.ics.uci.edu/ml/index.php)

In [93]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from numpy import loadtxt

In [94]:
data = loadtxt('diabetes.txt',delimiter=',')
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [95]:
type(data)

numpy.ndarray

In [96]:
labeled_data = pd.DataFrame(data=data, columns=["Number of times pregnant", "Plasma glucose concentration a 2 hours in an oral glucose tolerance test", "Diastolic blood pressure (mm Hg)", "Triceps skin fold thickness (mm)", "2-Hour serum insulin (mu U/ml)", "Body mass index", "Diabetes pedigree function", "Age (years)", "Labled_Dataset"])

In [97]:
labeled_data.head()

Number of times pregnant  \
0                       6.0   
1                       1.0   
2                       8.0   
3                       1.0   
4                       0.0   

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                              148.0                          
1                                               85.0                          
2                                              183.0                          
3                                               89.0                          
4                                              137.0                          

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                              72.0                              35.0   
1                              66.0                              29.0   
2                              64.0                               0.0   
3                              66.0                              23.0   
4                              40.0                              35.0   

   2-Hour serum insulin (mu U/ml)  Body mass index  \
0                             0.0             33.6   
1                             0.0             26.6   
2                             0.0             23.3   
3                            94.0             28.1   
4                           168.0             43.1   

   Diabetes pedigree function  Age (years)  Labled_Dataset  
0                       0.627         50.0             1.0  
1                       0.351         31.0             0.0  
2                       0.672         32.0             1.0  
3                       0.167         21.0             0.0  
4                       2.288         33.0             1.0

In [98]:
labeled_data.shape

(768, 9)

In [99]:
labeled_data.isnull().sum()

Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index                                                             0
Diabetes pedigree function                                                  0
Age (years)                                                                 0
Labled_Dataset                                                              0
dtype: int64

### Im ML you have to put lot of assumption, in DL you do not have to do it

In [100]:
labeled_data.describe()

Number of times pregnant  \
count                768.000000   
mean                   3.845052   
std                    3.369578   
min                    0.000000   
25%                    1.000000   
50%                    3.000000   
75%                    6.000000   
max                   17.000000   

       Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
count                                         768.000000                          
mean                                          120.894531                          
std                                            31.972618                          
min                                             0.000000                          
25%                                            99.000000                          
50%                                           117.000000                          
75%                                           140.250000                          
max                                           199.000000                          

       Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
count                        768.000000                        768.000000   
mean                          69.105469                         20.536458   
std                           19.355807                         15.952218   
min                            0.000000                          0.000000   
25%                           62.000000                          0.000000   
50%                           72.000000                         23.000000   
75%                           80.000000                         32.000000   
max                          122.000000                         99.000000   

       2-Hour serum insulin (mu U/ml)  Body mass index  \
count                      768.000000       768.000000   
mean                        79.799479        31.992578   
std                        115.244002         7.884160   
min                          0.000000         0.000000   
25%                          0.000000        27.300000   
50%                         30.500000        32.000000   
75%                        127.250000        36.600000   
max                        846.000000        67.100000   

       Diabetes pedigree function  Age (years)  Labled_Dataset  
count                  768.000000   768.000000      768.000000  
mean                     0.471876    33.240885        0.348958  
std                      0.331329    11.760232        0.476951  
min                      0.078000    21.000000        0.000000  
25%                      0.243750    24.000000        0.000000  
50%                      0.372500    29.000000        0.000000  
75%                      0.626250    41.000000        1.000000  
max                      2.420000    81.000000        1.000000

In [101]:
X = data[:,:8]
y = data[:,8]

In [102]:
X[:8]

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01],
       [5.000e+00, 1.160e+02, 7.400e+01, 0.000e+00, 0.000e+00, 2.560e+01,
        2.010e-01, 3.000e+01],
       [3.000e+00, 7.800e+01, 5.000e+01, 3.200e+01, 8.800e+01, 3.100e+01,
        2.480e-01, 2.600e+01],
       [1.000e+01, 1.150e+02, 0.000e+00, 0.000e+00, 0.000e+00, 3.530e+01,
        1.340e-01, 2.900e+01]])

In [103]:
y[:8]

array([1., 0., 1., 0., 1., 0., 1., 0.])

In [104]:
labeled_data.Labled_Dataset.value_counts()

0.0    500
1.0    268
Name: Labled_Dataset, dtype: int64

In [105]:
model = Sequential()   # constructor which initiate your tensorflow
model.add(Dense(24, input_dim=8, activation=tf.keras.layers.LeakyReLU(alpha=0.1)))  # input + Hidden layer 1,feature extractor 
model.add(Dense(12, activation=tf.keras.layers.LeakyReLU(alpha=0.3)))  # feature extractor, Hidden layer 2
model.add(Dense(6, activation='LeakyReLU'))   # feature extractor, Hidden layer 3
model.add(Dense(1, activation='sigmoid'))   # output layer
# number of class you want to predict

In [106]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 24)                216       
_________________________________________________________________
dense_13 (Dense)             (None, 12)                300       
_________________________________________________________________
dense_14 (Dense)             (None, 6)                 78        
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 7         
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [107]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=150,batch_size=100)

Epoch 1/150
8/8 [==============================] - 2s 3ms/step - loss: 5.1903 - accuracy: 0.5378
Epoch 2/150
8/8 [==============================] - 0s 3ms/step - loss: 2.8894 - accuracy: 0.6484
Epoch 3/150
8/8 [==============================] - 0s 3ms/step - loss: 2.5294 - accuracy: 0.6562
Epoch 4/150
8/8 [==============================] - 0s 4ms/step - loss: 1.8404 - accuracy: 0.6341
Epoch 5/150
8/8 [==============================] - 0s 2ms/step - loss: 1.4884 - accuracy: 0.6289
Epoch 6/150
8/8 [==============================] - 0s 2ms/step - loss: 1.1707 - accuracy: 0.6406
Epoch 7/150
8/8 [==============================] - 0s 3ms/step - loss: 0.9990 - accuracy: 0.6536
Epoch 8/150
8/8 [==============================] - 0s 4ms/step - loss: 0.8571 - accuracy: 0.6589
Epoch 9/150
8/8 [==============================] - 0s 4ms/step - loss: 0.7811 - accuracy: 0.6680
Epoch 10/150
8/8 [==============================] - 0s 3ms/step - loss: 0.7163 - accuracy: 0.6680
Epoch 11/150
8/8 [===========

8/8 [==============================] - 0s 4ms/step - loss: 0.5148 - accuracy: 0.7526
Epoch 85/150
8/8 [==============================] - ETA: 0s - loss: 0.5178 - accuracy: 0.77 - 0s 4ms/step - loss: 0.5203 - accuracy: 0.7461
Epoch 86/150
8/8 [==============================] - 0s 6ms/step - loss: 0.5725 - accuracy: 0.7214
Epoch 87/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5341 - accuracy: 0.7266
Epoch 88/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5363 - accuracy: 0.7174
Epoch 89/150
8/8 [==============================] - 0s 4ms/step - loss: 0.5295 - accuracy: 0.7292
Epoch 90/150
8/8 [==============================] - 0s 4ms/step - loss: 0.5142 - accuracy: 0.7539
Epoch 91/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5127 - accuracy: 0.7487
Epoch 92/150
8/8 [==============================] - 0s 4ms/step - loss: 0.5151 - accuracy: 0.7461
Epoch 93/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5377 - accuracy

In [108]:
loss_function,accuracy = model.evaluate(X,y)

24/24 [==============================] - 0s 3ms/step - loss: 0.4915 - accuracy: 0.7578


In [109]:
y_pred = model.predict(X)

In [110]:
y_pred[:5]

array([[0.6881431 ],
       [0.22884163],
       [0.87475014],
       [0.18261987],
       [0.81016093]], dtype=float32)

### NN gives the result in array, takes the  results the array

In [111]:
rounded = [round(x[0]) for x in y_pred]

In [112]:
print(rounded)

[1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 

## `Adam`

- Adam optimizitation is a technique in which you take exponential weighted average of your GD.
- You reach global minima faster with the help of Adam.
- Adam = Adagrad + RMSprop

## `END ------------------------------------------`