1. **Data**
2. **Preprocessing**
3. **Splitting**
4. **Building NN**
5. **Evaluate**

#### [Imported data from](https://archive.ics.uci.edu/ml/index.php)

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from numpy import loadtxt

In [2]:
data = loadtxt('diabetes.txt',delimiter=',')
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [3]:
type(data)

numpy.ndarray

In [4]:
labeled_data = pd.DataFrame(data=data, columns=["Number of times pregnant", "Plasma glucose concentration a 2 hours in an oral glucose tolerance test", "Diastolic blood pressure (mm Hg)", "Triceps skin fold thickness (mm)", "2-Hour serum insulin (mu U/ml)", "Body mass index", "Diabetes pedigree function", "Age (years)", "Labled_Dataset"])

In [12]:
labeled_data.head()

Number of times pregnant  \
0                       6.0   
1                       1.0   
2                       8.0   
3                       1.0   
4                       0.0   

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                              148.0                          
1                                               85.0                          
2                                              183.0                          
3                                               89.0                          
4                                              137.0                          

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                              72.0                              35.0   
1                              66.0                              29.0   
2                              64.0                               0.0   
3                              66.0                              23.0   
4                              40.0                              35.0   

   2-Hour serum insulin (mu U/ml)  Body mass index  \
0                             0.0             33.6   
1                             0.0             26.6   
2                             0.0             23.3   
3                            94.0             28.1   
4                           168.0             43.1   

   Diabetes pedigree function  Age (years)  Labled_Dataset  
0                       0.627         50.0             1.0  
1                       0.351         31.0             0.0  
2                       0.672         32.0             1.0  
3                       0.167         21.0             0.0  
4                       2.288         33.0             1.0

In [13]:
labeled_data.shape

(768, 9)

In [14]:
labeled_data.isnull().sum()

Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index                                                             0
Diabetes pedigree function                                                  0
Age (years)                                                                 0
Labled_Dataset                                                              0
dtype: int64

### `In ML you have to put lot of assumption, in DL you do not have to do it`

In [20]:
labeled_data.describe()

Number of times pregnant  \
count                768.000000   
mean                   3.845052   
std                    3.369578   
min                    0.000000   
25%                    1.000000   
50%                    3.000000   
75%                    6.000000   
max                   17.000000   

       Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
count                                         768.000000                          
mean                                          120.894531                          
std                                            31.972618                          
min                                             0.000000                          
25%                                            99.000000                          
50%                                           117.000000                          
75%                                           140.250000                          
max                                           199.000000                          

       Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
count                        768.000000                        768.000000   
mean                          69.105469                         20.536458   
std                           19.355807                         15.952218   
min                            0.000000                          0.000000   
25%                           62.000000                          0.000000   
50%                           72.000000                         23.000000   
75%                           80.000000                         32.000000   
max                          122.000000                         99.000000   

       2-Hour serum insulin (mu U/ml)  Body mass index  \
count                      768.000000       768.000000   
mean                        79.799479        31.992578   
std                        115.244002         7.884160   
min                          0.000000         0.000000   
25%                          0.000000        27.300000   
50%                         30.500000        32.000000   
75%                        127.250000        36.600000   
max                        846.000000        67.100000   

       Diabetes pedigree function  Age (years)  Labled_Dataset  
count                  768.000000   768.000000      768.000000  
mean                     0.471876    33.240885        0.348958  
std                      0.331329    11.760232        0.476951  
min                      0.078000    21.000000        0.000000  
25%                      0.243750    24.000000        0.000000  
50%                      0.372500    29.000000        0.000000  
75%                      0.626250    41.000000        1.000000  
max                      2.420000    81.000000        1.000000

### `scales of data are different, we can use standard scaler`

In [23]:
X = data[:,:8]
y = data[:,8]

In [24]:
X[:8]

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01],
       [5.000e+00, 1.160e+02, 7.400e+01, 0.000e+00, 0.000e+00, 2.560e+01,
        2.010e-01, 3.000e+01],
       [3.000e+00, 7.800e+01, 5.000e+01, 3.200e+01, 8.800e+01, 3.100e+01,
        2.480e-01, 2.600e+01],
       [1.000e+01, 1.150e+02, 0.000e+00, 0.000e+00, 0.000e+00, 3.530e+01,
        1.340e-01, 2.900e+01]])

In [25]:
y[:8]

array([1., 0., 1., 0., 1., 0., 1., 0.])

In [26]:
labeled_data.Labled_Dataset.value_counts()

0.0    500
1.0    268
Name: Labled_Dataset, dtype: int64

## `Model Building`

In [27]:
model = Sequential()   # constructor which initiate your tensorflow
model.add(Dense(24, input_dim=8, activation=tf.keras.layers.LeakyReLU(alpha=0.1)))  # input + Hidden layer 1,feature extractor 
model.add(Dense(12, activation=tf.keras.layers.LeakyReLU(alpha=0.3)))  # feature extractor, Hidden layer 2
model.add(Dense(6, activation='LeakyReLU'))   # feature extractor, Hidden layer 3
model.add(Dense(1, activation='sigmoid'))   # output layer
# number of class you want to predict

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 24)                216       
                                                                 
 dense_1 (Dense)             (None, 12)                300       
                                                                 
 dense_2 (Dense)             (None, 6)                 78        
                                                                 
 dense_3 (Dense)             (None, 1)                 7         
                                                                 
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


#### 24\*8+24(bias)=216
#### 12\*24+12(bias)=300
#### 6\*12+6(bias)=78
#### 1\*6+1(bias)=7

In [29]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=150,batch_size=100)

Epoch 1/150
8/8 [==============================] - 4s 4ms/step - loss: 4.2300 - accuracy: 0.5365
Epoch 2/150
8/8 [==============================] - 0s 4ms/step - loss: 2.5754 - accuracy: 0.4310
Epoch 3/150
8/8 [==============================] - 0s 3ms/step - loss: 2.1362 - accuracy: 0.5938
Epoch 4/150
8/8 [==============================] - 0s 4ms/step - loss: 1.8510 - accuracy: 0.4544
Epoch 5/150
8/8 [==============================] - 0s 5ms/step - loss: 1.4657 - accuracy: 0.5755
Epoch 6/150
8/8 [==============================] - 0s 4ms/step - loss: 1.2757 - accuracy: 0.5221
Epoch 7/150
8/8 [==============================] - 0s 4ms/step - loss: 1.1420 - accuracy: 0.5599
Epoch 8/150
8/8 [==============================] - 0s 7ms/step - loss: 1.0311 - accuracy: 0.5508
Epoch 9/150
8/8 [==============================] - 0s 3ms/step - loss: 0.9418 - accuracy: 0.5964
Epoch 10/150
8/8 [==============================] - 0s 4ms/step - loss: 0.8622 - accuracy: 0.6068
Epoch 11/150
8/8 [===========

8/8 [==============================] - 0s 6ms/step - loss: 0.5882 - accuracy: 0.7070
Epoch 85/150
8/8 [==============================] - 0s 5ms/step - loss: 0.5625 - accuracy: 0.7161
Epoch 86/150
8/8 [==============================] - 0s 5ms/step - loss: 0.6227 - accuracy: 0.6771
Epoch 87/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5786 - accuracy: 0.7227
Epoch 88/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5630 - accuracy: 0.7135
Epoch 89/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5900 - accuracy: 0.7174
Epoch 90/150
8/8 [==============================] - 0s 5ms/step - loss: 0.5548 - accuracy: 0.7279
Epoch 91/150
8/8 [==============================] - 0s 4ms/step - loss: 0.5595 - accuracy: 0.7240
Epoch 92/150
8/8 [==============================] - 0s 4ms/step - loss: 0.5562 - accuracy: 0.7370
Epoch 93/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5550 - accuracy: 0.7370
Epoch 94/150
8/8 [===============

### `Evaluation`

In [33]:
loss_function,accuracy = model.evaluate(X,y)

24/24 [==============================] - 0s 2ms/step - loss: 0.5160 - accuracy: 0.7370


In [34]:
y_pred = model.predict(X)

In [35]:
y_pred[:5]

array([[0.6122564 ],
       [0.1457144 ],
       [0.91336715],
       [0.10511836],
       [0.68766373]], dtype=float32)

### `problem with sigmoid is it is not giving us 0's or 1's`

### `NN gives the result in array, takes the results in array`

In [37]:
for x in y_pred:
    print(x[0])

0.6122564
0.1457144
0.91336715
0.105118364
0.68766373
0.2995298
0.27028656
0.51916856
0.37326807
0.022697628
0.2258538
0.8139175
0.44992077
0.47409776
0.8320993
0.38773274
0.21982986
0.36579508
0.39031625
0.11424154
0.2793346
0.18945852
0.77396995
0.25984982
0.52850795
0.51184356
0.64428496
0.071843654
0.5208183
0.2528801
0.33546346
0.5831785
0.111251295
0.050950587
0.4128669
0.4839973
0.65414053
0.3774548
0.24115777
0.520269
0.49308172
0.52831304
0.11804891
0.261513
0.7046456
0.929198
0.6298512
0.09594059
0.47326133
0.32449108
0.07953608
0.17852426
0.1304298
0.6454929
0.6937398
0.21278355
0.9178138
0.099736124
0.51354903
0.22741652
0.2779734
0.58330274
0.0666154
0.4624808
0.49157003
0.20496511
0.11765337
0.21579292
0.1157386
0.19723609
0.121301055
0.5832332
0.53743136
0.15466464
0.08717877
0.29360694
0.0842168
0.26762676
0.73922974
0.21628326
0.5986538
0.2464239
0.08582744
0.13842729
0.344072
0.245576
0.4706249
0.08647907
0.5908439
0.18078208
0.1798935
0.102849424
0.17423442
0.2822448

In [39]:
rounded = [round(x[0]) for x in y_pred]

In [40]:
print(rounded)

[1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 

## `Adam`

- Adam optimizitation is a technique in which you take **exponential weighted average of your GD**.
- **You reach global minima faster with the help of Adam**.
- **Adam = Adagrad + RMSprop**

## `Dense is a feed forword neural network`
## `Outliers vs Noise`
## `Treat outliers which is not even possible/cannot happen/happening at a very very rare case`
## `Dynamicness in the data is not outliers`

## `END ------------------------------------------`