In [1]:
import numpy as np
import os 


In [2]:
u = np.array([3,4])
v = np.array([30, 40])

In [3]:
print(u, v)

[3 4] [30 40]


In [5]:
print(np.linalg.norm(u))
print(np.linalg.norm(v))

5.0
50.0


In [6]:
def direction(x):
  return x/np.linalg.norm(x)

In [7]:
u_direction = direction(u)
v_direction = direction(v)

In [8]:
print(u_direction)

[0.6 0.8]


In [9]:
print(v_direction)

[0.6 0.8]


In [10]:
print(np.linalg.norm(u_direction))

1.0


In [11]:
def dot_product(x, y):
  result=0
  for i in range(len(x)):
    result = result+x[i]*y[i]
  return(result)

In [12]:
x = [3, 5]
y= [8,3]
print(dot_product(x, y))

39


In [15]:
import math
def geometric_dot_product(x,y,theta):
  x_norm = np.linalg.norm(x)
  y_norm = np.linalg.norm(y)
  return x_norm*y_norm*math.cos(math.radians(theta))

In [19]:
print(np.linalg.norm(x)*np.linalg.norm(y))
print(geometric_dot_product(x, y, theta=30))

49.8196748283246
43.14510400960925


In [ ]:
# 3x + 4y = 5
# 5x+7y = 8
# 8x+9y=4

In [20]:
a = np.array([[3,4],[5,7], [8, 9]])
b = np.array([[5], [8], [4]])

In [22]:
#c = np.linalg.solve(a,b)
c = np.linalg.lstsq(a,b)[0]
print(c)

[[-4.2585034 ]
 [ 4.23809524]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [26]:
print(8*c[0]+9*c[1])

[4.07482993]


In [27]:
c =np.array([3,4])
z=np.array([5,6])

In [28]:
print(c, z)

[3 4] [5 6]


In [29]:
b = list(zip(z, c))

In [30]:
print(b)

[(5, 3), (6, 4)]


In [31]:
print(type(b[0]))

<class 'tuple'>


In [32]:
A = np.array(b)

In [33]:
print(A)
print(type(A))
print(A.shape)


[[5 3]
 [6 4]]
<class 'numpy.ndarray'>
(2, 2)


In [34]:
result = A+3

In [35]:
print(result)

[[8 6]
 [9 7]]


In [36]:
B = np.random.randn(2,2)

In [37]:
print(B)

[[-0.39677546 -0.72644765]
 [-1.08706025  0.23997968]]


In [38]:
np.matmul(A, B)

array([[-5.24505808, -2.91229923],
       [-6.72889379, -3.3987672 ]])

In [40]:
print(A.dot(B))
print(np.dot(A, B))

[[-5.24505808 -2.91229923]
 [-6.72889379 -3.3987672 ]]
[[-5.24505808 -2.91229923]
 [-6.72889379 -3.3987672 ]]
