# `Tensorflow`
- CPU process in series, GPU process parallely

In [3]:
# !pip install --user tensorflow
# !pip install --user numpy 

In [1]:
import tensorflow as tf
import numpy as np
import scipy as sc
import math

In [4]:
string_val = tf.Variable('Innomatics Research Labs', tf.string)
int_val = tf.Variable(34, tf.int32)
float_val = tf.Variable(3.4, tf.float32)
print(string_val, int_val, float_val)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Innomatics Research Labs'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.4>


In [5]:
print(string_val)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Innomatics Research Labs'>


In [6]:
val = tf.Variable("Innomatics Research Labs")
print(val)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Innomatics Research Labs'>


In [8]:
rank1_tensor = tf.Variable([[['Test', "deep"], ['Learning', 'AI']], [['ML', 'Analytics'], ['DL', 'ML']]])
print(rank1_tensor)
print(tf.rank(rank1_tensor))

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=string, numpy=
array([[[b'Test', b'deep'],
        [b'Learning', b'AI']],

       [[b'ML', b'Analytics'],
        [b'DL', b'ML']]], dtype=object)>
tf.Tensor(3, shape=(), dtype=int32)


In [9]:
rank1_tensor[1][0][0]

<tf.Tensor: shape=(), dtype=string, numpy=b'ML'>

In [10]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [11]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [12]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [13]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [15]:
matrix = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16, 17, 18, 19, 20]]
tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [16]:
print(tensor[0,3])
print(tensor[:, 0])
print(tensor[0])

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [17]:
val = tf.Variable(14, tf.int32)
val.assign(54)
val = val.assign_add(20)
print(val)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=74>


In [18]:
val = tf.Variable(14, tf.int32) 
val+34

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [20]:
val = tf.constant([1,2,3,4,5,6])
val  = val.assign_add(3)
print(val)

AttributeError: ignored

In [21]:
x = tf.placeholder('float', None)

AttributeError: ignored

## `END --------------------------------------------------`