In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy import *
import sympy as sympy

In [2]:
x= .5 
print(x)

0.5


In [30]:
o = np.array(2)
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3], [4,5,6]])
c = np.array([[[1,2,3,4,5], [5,6,7,8,9]], [[1,2,3,4,5], [5,4,3,2,1]]])

In [6]:
print(a.shape)

(5,)


In [7]:
print(a.ndim)

1


In [31]:
print(o.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


In [38]:
arr= np.array([1,2,3,4], ndmin=1)

In [34]:
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4]
(4,)
1


In [40]:
arr = arr.reshape((2,2))

In [36]:
print(arr)

[[1 2]
 [3 4]]


In [37]:
arr.ndim

2

In [42]:
print(arr.shape)

(2, 2)


In [41]:
vals = arr.reshape((arr.shape[0], arr.shape[1]))

In [43]:
B = np.random.randn(2,2)
print(B)

[[ 0.91573881  1.13068086]
 [ 1.39813206 -0.36849272]]


In [44]:
A = np.random.randn(2,2)
print(A)

[[-0.41205363  0.10148153]
 [ 1.1294911   0.45407244]]


In [45]:
Results = A +B

In [46]:
print(Results)

[[0.50368518 1.23216238]
 [2.52762317 0.08557972]]


In [47]:
Results*2

array([[1.00737036, 2.46432477],
       [5.05524633, 0.17115944]])

In [48]:
np.matmul(A, B)

array([[-0.23544893, -0.50329636],
       [ 1.66917208,  1.10977158]])

In [49]:
result_inv = np.linalg.inv(Results)

In [50]:
print(result_inv)

[[-0.027864    0.40118112]
 [ 0.82297163 -0.16399542]]


In [51]:
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))

In [52]:
print(A)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
print(A.T)

[[0 2 4]
 [1 3 5]]


In [56]:
I = np.identity(3, dtype=float)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
print(B.T.dot(A.T))
print('The Matrix is Identical to :')
print((A.dot(B)).T)

[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
The Matrix is Identical to :
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
